"""outbox event add attempt and next_attempt_at fields

Revision ID: 25ca663e8b6b
Revises: 052113a3d64e
Create Date: 2026-08-08 22:44:07.595898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ca663e8b6b'
down_revision: Union[str, Sequence[str], None] = '052113a3d64e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('attempt', sa.Integer(), server_default='1', nullable=False))
    op.add_column('outbox_events', sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_events', 'next_attempt_at')
    op.drop_column('outbox_events', 'attempt')
    # ### end Alembic commands ###
